#!/usr/bin/env python3
import os
import json
import hashlib
from datetime import datetime

MANIFEST_PATH = "ci/integrity-manifest.json"

# Core files that should be protected from unauthorized/silent tampering.
PROTECTED_PATTERNS = [
    "setup.sh",
    "install.sh",
    "scripts/sync_to_target.py",
    "adapters/CURSOR_RULES.tpl",
    "adapters/TRAE_RULES.tpl",
    "adapters/CLAUDE_CODE_RULES.tpl",
    "adapters/AGENTS.md.tpl",
    "profiles/strict.yaml",
    "profiles/default.yaml",
    "profiles/legacy.yaml"
]

def calculate_sha256(filepath):
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def update_manifest():
    manifest = {
        "_meta": {
            "description": "Anti-Tampering Integrity Manifest",
            "last_updated": datetime.now().isoformat(),
            "instruction": "Do NOT edit this file manually. Run `python3 scripts/update_integrity_manifest.py` after legitimate changes."
        },
        "hashes": {}
    }

    for pattern in PROTECTED_PATTERNS:
        if os.path.exists(pattern):
            manifest["hashes"][pattern] = calculate_sha256(pattern)
            print(f"🔒 Protected: {pattern}")
        else:
            print(f"⚠️ Warning: Expected protected file not found: {pattern}")

    os.makedirs(os.path.dirname(MANIFEST_PATH), exist_ok=True)
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print(f"\n✅ Integrity manifest updated successfully at {MANIFEST_PATH}")

if __name__ == "__main__":
    update_manifest()
